### ISSUE TITLE
No sort support?

### ISSUE THREAD

**Issue by CodeOtter** [blakmatrix/node-zendesk#111]
https://github.com/blakmatrix/node-zendesk/blob/master/lib/client/search.js#L19

I see no query sorting?

**Comment by nnabuuu** [comment]
Looks like it's not implemented in node-zendesk yet. You are welcomed to contribute this Endpoint : ) 

I believe an /*Optional*/ parameter should be added for this function.

**Comment by baohouse** [comment]
Definitely not a trivial change to support optional parameters on the existing methods. Assuming you pass in sort options as an object:

`{
  sort_by: 'created_at',
  sort_order: 'asc'
}`

The methods would have to be updated, e.g. (and this is not the most elegant solution, but just something I quickly whipped up for my own project)

`Tickets.prototype.listByUserRequested = function(userID) {
  var cb = arguments[arguments.length - 1]; // Last argument must always be callback
  var args = ['users', userID, 'tickets', 'requested'];
  if (typeof arguments[1] === 'object') { args.push(arguments[1]); }
  this.requestAll('GET', args, cb);
};`

Another problem is which of these methods should get the optional parameter support, because according to [Zendesk](https://developer.zendesk.com/rest_api/docs/core/introduction#pagination)

> Some lists can be ordered by transmitting a sort_order=desc or sort_order=asc parameter to the end point. Whether a specific list can be ordered is specified in the documentation for that specific resource.

I've observed some resources like Ticket Comments mentioning nothing about supporting sorting, and yet when I did some testing, it _did_ work. So I'd hate to have to rely on evolving documentation and selectively choose which methods should support optional sort parameters.
