### ISSUE TITLE
"Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by rublev** [blakmatrix/node-zendesk#184]
Short of removing this library I'm unsure of how to resolve these warnings:

I took a look at line 85 in node-zendesk/lib/client.js and it looks like a dynamic require is causing the problem?

```
partsToAdd.forEach(function (k) {
  exports[k] = require(clientPath + k.toLowerCase())[k];
});
```

```
WARNING in ./~/node-zendesk/lib/client.js
85:17-54 Critical dependency: the request of a dependency is an expression

WARNING in ./~/nconf/~/yargs/lib/parser.js
325:23-71 Critical dependency: the request of a dependency is an expression

WARNING in ./~/center-align/utils.js
8:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by blakmatrix** [comment]
I think this may be an issue with your webpack require contexts, feel free to reopen if you think it's on our end.

**Comment by magic-madrigal** [comment]
I agree with @rublev, this is on the node-zendesk side.

Due to the dynamic require, Webpack is unable to bundle the 3 libs listed above. 

Simply separating them our into there own require statements would resolve this issue, or using require.context.

Reference Links:
https://github.com/webpack/webpack/issues/2675
https://github.com/dcodeIO/protobuf.js/issues/339
