### ISSUE TITLE
Associate Jira Issue with Zendesk Ticket

### ISSUE THREAD

**Issue by romulets** [blakmatrix/node-zendesk#238]
Hi,

I'm trying to associate a Jira Issue with a Zendesk Ticket.

The API is documented [https://developer.zendesk.com/rest_api/docs/services/jira](here)

Is there any way of doing this association through this library?

**Comment by TooManyJohns** [comment]
Hey there, I actually just finished implementing this into a custom version of this repo, if anyone still needs this added (since it seems no one is active on this repo anymore) I can happily provide a working implementation for them , just hit me up with a response here 👍 (If I have time, I can actually get a PR up for people to pull down 😄 ) but I guess it'll be if anyone needs it for now 🤷‍♂️
