### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by sebastiansandqvist** [blakmatrix/node-zendesk#251]
Wondering if type definitions could be added so that Typescript users can easily use the ZenDesk API

**Comment by Pwuts** [comment]
`@types/node-zendesk` does exist but it is not complete, e.g. the type of the second and third arguments of `ZendeskCallback` is specified as `unknown`, giving errors when trying to access its properties.

**Comment by Pwuts** [comment]
@blakmatrix any comment on why you've closed this issue?

**Comment by blakmatrix** [comment]
Cowboy Theatrics *shrug* what is "@types/node-zendesk" ? I'm doing my best to get back into trying to maintain this.

**Comment by blakmatrix** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f667351f064837dec421df5abadae50c5a0ba698/types/node-zendesk/node-zendesk-tests.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f667351f064837dec421df5abadae50c5a0ba698/types/node-zendesk/index.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f667351f064837dec421df5abadae50c5a0ba698/types/node-zendesk/tsconfig.json

**Comment by blakmatrix** [comment]
#276

**Comment by mattcasey** [comment]
Hi, I am just replying here since you've left the issue open. Is there any particular way you'd like help? I'd like to share any types that I need to add as I'm working with the module. In particular I'll be working with macros and help center api, and the methods are implemented but missing from @types/node-zendesk. I already started a fork: https://github.com/mattcasey/DefinitelyTyped/tree/node-zendesk. Do you mind if I just submit all my changes at once when I've finished our first iteration (I'm going to need maybe 5-6 methods?)?

**Comment by stormsa** [comment]
Hello I have open a issue right there : https://github.com/blakmatrix/node-zendesk/issues/331 
It's seems @types/node-zendesk  does not match your code.
Also your project does not provide pagination information ? 
Object are destructed and does not match zendesk api I found.
Please tell me if it's normal or maybe my version don't match. 
Thank you for your help
