### ISSUE TITLE
Release `fetch` changes

### ISSUE THREAD

**Issue by sgerrand** [blakmatrix/node-zendesk#372]
Now that this package uses Node.js's `fetch` instead of `request` thanks to @teebot's work in https://github.com/blakmatrix/node-zendesk/pull/368, do you plan to release a version with these changes?

**Comment by sgerrand** [comment]
👋 @blakmatrix, what do you think?

**Comment by blakmatrix** [comment]
Yes, @sgerrand thanks for following up, with the fetch changes there has been a decent refactor, I need to test a few more aspects and write up a changelog, I was hoping also to get a more comprehensive API documentation out as well but I may punt that to a later release as it has proved to be a bit more intensive than I originally thought (in addition to adding/removing API endpoints due to the Zendesk API changing.
I am hoping to get a release out this week, things have suddenly become very busy for me in the past few weeks, but I'm going to do my best to get a release out this week.

**Comment by sgerrand** [comment]
Thank you for sharing your plans for this and also for the attention that you're paying to this change. For what it's worth, I've been using this in the wild for the past from the `HEAD` of the `master` branch with no problems.

**Comment by blakmatrix** [comment]
Done https://github.com/blakmatrix/node-zendesk/releases/tag/v4.0.0 :) I realized the docs are still a ways of fand I don't think this release should have too many breaking changes. LMK how it goes and thank you for the feedback and kudos :)
