### ISSUE TITLE
nconf collision

### ISSUE THREAD

**Issue by leore** [blakmatrix/node-zendesk#54]
We use nconf in our app. When we integrate node-zendesk the nconf collides and causes our app to break. After looking into how nconf is used in node-zendesk I think it needs to be declared at the top of client.js to work correctly and not collide with other apps use nconf.

**Comment by blakmatrix** [comment]
If you do an ad-hoc add of what you're mentioning does it work?

**Comment by mgartner** [comment]
I've tried moving the nconf requirement to the top of the file, but still have no success. I'm thinking that maybe this is a shortcoming of nconf, and I've submitted an issue: flatiron/nconf#142.

That being said, I'm wondering if nconf is really necessary in packages such as this one, where it will often be required as a dependency in other projects. I don't understand the use case where environment variables and command line arguments would be useful. The inputs required for this library are very straight forward, and passing them in from the command line or as environment variables is the responsibility of the user, not the library, IMO.

If I submitted a PR to rip out nconf and the env() and argv() features it provides, would you be open to merging it?

**Comment by blakmatrix** [comment]
Short answer, yes I would be open to this.

I've been mulling over this for a while now, there are still some executing
scripts directly from command line with the library as is.

I've been at a loss for how to make this just a library, yet also provide a
easy way for others to continue using it as originally designed. Perhaps
converting it to a pure library while providing a section in the readme as
how to do this simply will suffice (as this is more a library anyways, and
I agree this is something tthe integrator should be responsible for--
because if we were to split that feature out it'd be nothing but a
commandline env var wrapper).



-- 
Farrin A. Reid
http://www.linkedin.com/in/farrinreid

**Comment by mgartner** [comment]
Ya I think you could convert this to solely a library, and create a new repository for a node-zendesk CLI.

**Comment by blakmatrix** [comment]
@leore @mgartner I just made a change that should fix this issue #60 , please verify once i get the new version out the lines added are https://github.com/blakmatrix/node-zendesk/blob/master/lib/client.js#L22 and https://github.com/blakmatrix/node-zendesk/blob/master/lib/client.js#L47 , feel free to open if either of you think it needs to be reopened.
