### ISSUE TITLE
Helpcenter returns 404

### ISSUE THREAD

**Issue by mzelmanovich** [blakmatrix/node-zendesk#82]
I have used the following for my createClient:

```
var client = zendesk.createClient({
  username:  name
  token:    toke,
  remoteUri: 'https://test.zendesk.com/api/v2',
  helpcenter: true
});
```

It returns nothing but 404's for all the helpcenter methods. I have had no major issues accessing ticket information. Have verified that api can be accessed by using CURL. 

**_Update**_ if helpcenter is true you still need to add help_center to the uri. As you can see above I did not and this caused the 404's. This seems like a minor thing but is annoying and counter intuitive.

**Comment by ckumar1** [comment]
Although this is related to issue #80, it's slightly different because the remote_uri will never be set to the correct help_center path because the subdomain parameter is not provided when initializing the client. 

Additionally, if the helpcenter parameter is set to true, is it expected that the client would only have access to the helpcenter api methods, and none of the core api methods?

**Comment by nnabuuu** [comment]
1. That is not the remoteUri for helpcenter, helpcenter support following 2 kinds of remoteUri:

`http://test.zendesk.com/hc/api/v2` or `https://test.zendesk.com/api/v2/help_center`

In you case, I suggest you use `subdomain: 'test'` instead, so that node-zendesk will organize the remoteUri for you. Sorry I haven't made it smarter to check the remoteUri : (

2. You could create another client using another zendesk.createClient({}), currently it is designed like that to isolate the logic.

**Comment by nnabuuu** [comment]
Hi @ckumar1 , I saw your update. I agree with you, and I will come up with a PR to fix this : )
